---
# tasks file for node_exporter

- name: Installation des prérequis (gpg, software-properties-common)
  ansible.builtin.apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Ajout de la clé gpg grafana
  ansible.builtin.apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no

- name: Ajout des repository grafana
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    validate_certs: no

- name: Installation de grafana
  ansible.builtin.apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  
- name: Changement du mot de passe admin pour l'accès GUI
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: "{{ item.before }}"
    line: "{{ item.after }}"
  with_items:
  - { before: "^;admin_user = admin", after: "admin_user = {{ grafana_adminUser }}"}
  - { before: "^;admin_password = admin", after: "admin_password = {{ grafana_adminPassword }}"}
  notify: restart_grafana

- name: Activation du service grafana-server au démarrage
  systemd:
    name: grafana-server
    state: started
    enabled: yes


- name: Ajout de la datasource prometheus
  community.grafana.grafana_datasource:
    name: "prometheus-local"
    grafana_url: "http://127.0.0.1:3000"
    grafana_user: "{{ grafana_adminUser }}"
    grafana_password: "{{ grafana_adminPassword }}"
    ds_type: "prometheus"
    ds_url: "http://127.0.0.1:9090"
  changed_when: false

- name: Attendre que grafana soit up
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

- name: Installation du dashboard node-exporter
  get_url:
    url: https://raw.githubusercontent.com/rfrail3/grafana-dashboards/master/prometheus/node-exporter-full.json
    dest: /var/lib/grafana/node-exporter.json
    mode: '0755'

- name: Activation du dashboard node exporter
  template:
    src: dashboard-node-exporter.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard-node-exporter.yml
    mode: 0755
  notify: restart_grafana

- meta: flush_handlers


