# - name: installation du role node_exporter
#   hosts: all
#   become: yes
#   roles:
#   - node_exporter

- name: installation des rôles prometheus & grafana
  hosts: monitor
  become: yes
  roles:
  - prometheus
  - grafana