---
# vars file for node_exporter

prometheus_dirConf: "/etc/prometheus"
prometheus_retentionTime: "365d"
prometheus_scrapeInterval: "30s"
prometheus_node_exporter: true
prometheus_node_exporter_group: "all"
prometheus_env: "production"
prometheus_varConf:
  global:
    scrape_interval: "{{ prometheus_scrapeInterval }}"
    evaluation_interval: 5s
    external_labels:
      env: '{{ prometheus_env }}'
  scrape_configs:
    - job_name: prometheus
      scrape_interval: 5m
      static_configs:
        - targets: ['{{ inventory_hostname }}:9090']