---
# tasks file for node_exporter


- name: Installe ou mets à jour prometheus
  ansible.builtin.apt:
    name: prometheus
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Arguments pour le fichier de configuration prometheus
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus

- name: Modification du fichier de configuration prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dirConf }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: reload_prometheus

- meta: flush_handlers

- name: Activation au démarrage de prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes

